# Generated by Django 3.1.7 on 2021-04-07 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionProjet', '0002_auto_20210408_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200)),
                ('description_reclamation', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_traitement', models.DateField()),
                ('date_solution', models.DateField()),
                ('statut', models.CharField(max_length=200)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionProjet.utilisateur')),
            ],
        ),
    ]
