# Generated by Django 3.1.7 on 2021-04-07 12:27

import GestionProjet.custom_validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_article', models.CharField(max_length=100, null=True)),
                ('nom_article', models.CharField(max_length=100, null=True)),
                ('image', models.FileField(blank=True, upload_to='image')),
                ('desc_article', models.TextField()),
                ('dispo_article', models.IntegerField()),
                ('categorie', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=100, null=True)),
                ('description_projet', models.TextField()),
                ('adresse_projet', models.CharField(max_length=200, null=True)),
                ('date_ajout_projet', models.DateTimeField(auto_now_add=True, null=True)),
                ('cout_projet', models.FloatField(null=True, validators=[GestionProjet.custom_validators.validate_interval])),
                ('delai_projet', models.PositiveIntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('etat_projet', models.CharField(choices=[('a faire', 'a faire'), ('en cours', 'en cours'), ('terminé', 'terminé')], max_length=200, null=True)),
                ('caracteristique_projet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('date_naiss', models.DateField()),
                ('adresse', models.CharField(max_length=800, null=True)),
                ('email', models.CharField(max_length=800, null=True)),
                ('telephone', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chef_Projet',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GestionProjet.utilisateur')),
            ],
            bases=('GestionProjet.utilisateur',),
        ),
        migrations.CreateModel(
            name='Responsable_Projet',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GestionProjet.utilisateur')),
            ],
            bases=('GestionProjet.utilisateur',),
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_tache', models.CharField(max_length=200, null=True)),
                ('description_tache', models.TextField()),
                ('mots_clés', models.TextField(blank=True, null=True)),
                ('demarche_tache', models.TextField(blank=True, null=True)),
                ('difficulté_tache', models.TextField(blank=True, null=True)),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionProjet.projet')),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='chef_projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionProjet.chef_projet'),
        ),
        migrations.CreateModel(
            name='ProjArti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProjet.article')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProjet.projet')),
                ('chef_projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionProjet.chef_projet')),
            ],
        ),
    ]
